name: Rust

on:
  push:
    branches: [master, test]
  pull_request:
    branches: [master, test]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.platform.runner }}
    strategy:
      matrix:
        platform:
          - runner: ubuntu-24.04
          - runner: ubuntu-22.04
          - runner: windows-2022
          - runner: windows-2025
          - runner: macos-13
          - runner: macos-14
          - runner: macos-15
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: true
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run tests in release
      run: cargo test --verbose --release
